# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'WesifyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # TensorFlow Lite for iOS
  pod 'TensorFlowLite', '~> 2.0'

end



